---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the required packages in Debian derivatives
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items: ntp_pkgs
  become: yes
  when: ansible_os_family == 'Debian'

- name: Copy the ntp.conf template file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  become: yes
  notify: 
    - restart ntp
