---
- include: dynamic_groups.yml

- hosts: 127.0.0.1
  roles:
    - { role: aws_services }
    - { role: deploy }
  
- hosts: base_ec2
  gather_facts: True
  roles:
    - { role: base, ansible_connection: ssh, ansible_user: ubuntu, action: "pre_reboot" }
    - ntp

- hosts: 127.0.0.1
  roles:
      - { role: base, action: "reboot" }
  
  post_tasks:
    - set_fact:
        ec2_name: '{{ service }}-{{ env }}'

    - set_fact:
        ec2_ip: '{{ ec2_name | get_instance(aws_region, state="running") }}'
    
    - name: Add base instances to host group
      add_host:
        name: "{{ ec2_ip }}"
        groups: "{{ service }}_ec2_final"
        ansible_ssh_user: ansible
        ansible_sudo_user: root

- hosts: base_ec2_final
  gather_facts: True
  roles:
    - { role: base, ansible_connection: ssh, ansible_user: ansible, action: "post_reboot" }

- hosts: 127.0.0.1
  gather_facts: false
  roles:
    - { role: ami_builder }
